-- Seed 80 API connectors into all tenant schemas
DO $seed$
DECLARE
  tenant RECORD;
BEGIN
  FOR tenant IN SELECT schema_name FROM tenants WHERE is_active = true
  LOOP
    EXECUTE format($ins$
      INSERT INTO %I.connectors (name, type, provider, region, auth_method, is_active) VALUES
      ('Twilio_SendGrid','HTTP_API','Twilio','global','API_KEY',true),
      ('Vonage_Nexmo','HTTP_API','Vonage','global','API_KEY',true),
      ('MessageBird','HTTP_API','MessageBird','global','API_KEY',true),
      ('Sinch','HTTP_API','Sinch','global','API_KEY',true),
      ('Infobip','HTTP_API','Infobip','global','BASIC',true),
      ('Plivo','HTTP_API','Plivo','global','API_KEY',true),
      ('Bandwidth','HTTP_API','Bandwidth','global','BASIC',true),
      ('Telnyx','HTTP_API','Telnyx','global','API_KEY',true),
      ('Telesign','HTTP_API','Telesign','global','BASIC',true),
      ('RouteMobile','HTTP_API','RouteMobile','global','API_KEY',true),
      ('Google_Jibe','RCS','Google','global','BASIC',true),
      ('Mavenir_RCS','RCS','Mavenir','global','API_KEY',true),
      ('Samsung_RCS','RCS','Samsung','global','API_KEY',true),
      ('Infobip_RCS','RCS','Infobip','global','API_KEY',true),
      ('Flash_Call_Global','FLASH_SMS','FlashCall','global','API_KEY',true),
      ('Sinch_Flash','FLASH_SMS','Sinch','global','API_KEY',true),
      ('ATT_API','HTTP_API','ATT','americas','API_KEY',true),
      ('Verizon_GW','HTTP_API','Verizon','americas','API_KEY',true),
      ('TMobile_US','HTTP_API','T-Mobile','americas','API_KEY',true),
      ('Bell_Canada','HTTP_API','Bell','americas','BASIC',true),
      ('Rogers_CA','HTTP_API','Rogers','americas','API_KEY',true),
      ('Claro_BR','HTTP_API','Claro','americas','BASIC',true),
      ('Vivo_BR','HTTP_API','Vivo','americas','API_KEY',true),
      ('ATT_RCS','RCS','ATT','americas','API_KEY',true),
      ('Vodafone_DE','HTTP_API','Vodafone','europe','API_KEY',true),
      ('TMobile_DE','HTTP_API','T-Mobile','europe','BASIC',true),
      ('Orange_FR','HTTP_API','Orange','europe','BASIC',true),
      ('SFR_FR','HTTP_API','SFR','europe','API_KEY',true),
      ('Movistar_ES','HTTP_API','Movistar','europe','BASIC',true),
      ('TIM_IT','HTTP_API','TIM','europe','BASIC',true),
      ('EE_UK','HTTP_API','EE','europe','API_KEY',true),
      ('Vodafone_UK','HTTP_API','Vodafone','europe','BASIC',true),
      ('KPN_NL','HTTP_API','KPN','europe','API_KEY',true),
      ('Vodafone_RCS_EU','RCS','Vodafone','europe','API_KEY',true),
      ('Telekom_RCS','RCS','DeutscheTelekom','europe','BASIC',true),
      ('Swisscom_Flash','FLASH_SMS','Swisscom','europe','API_KEY',true),
      ('Etisalat_UAE','HTTP_API','Etisalat','middle_east','API_KEY',true),
      ('Du_UAE','HTTP_API','Du','middle_east','BASIC',true),
      ('STC_Saudi','HTTP_API','STC','middle_east','API_KEY',true),
      ('Zain_KSA','HTTP_API','Zain','middle_east','API_KEY',true),
      ('Ooredoo_KW','HTTP_API','Ooredoo','middle_east','API_KEY',true),
      ('Omantel','HTTP_API','Omantel','middle_east','BASIC',true),
      ('Batelco_BH','HTTP_API','Batelco','middle_east','API_KEY',true),
      ('Etisalat_RCS','RCS','Etisalat','middle_east','API_KEY',true),
      ('Mobily_Flash','FLASH_SMS','Mobily','middle_east','API_KEY',true),
      ('MTN_Nigeria','HTTP_API','MTN','africa','API_KEY',true),
      ('Airtel_NG','HTTP_API','Airtel','africa','BASIC',true),
      ('Vodacom_SA','HTTP_API','Vodacom','africa','API_KEY',true),
      ('Safaricom_KE','HTTP_API','Safaricom','africa','API_KEY',true),
      ('Orange_Egypt','HTTP_API','Orange','africa','API_KEY',true),
      ('Vodafone_EG','HTTP_API','Vodafone','africa','API_KEY',true),
      ('Maroc_Telecom','HTTP_API','MarocTelecom','africa','BASIC',true),
      ('MTN_RCS_Africa','RCS','MTN','africa','API_KEY',true),
      ('Safaricom_Flash','FLASH_SMS','Safaricom','africa','API_KEY',true),
      ('Telstra_AU','HTTP_API','Telstra','asia_pacific','API_KEY',true),
      ('Optus_AU','HTTP_API','Optus','asia_pacific','BASIC',true),
      ('Spark_NZ','HTTP_API','Spark','asia_pacific','API_KEY',true),
      ('Telkomsel_ID','HTTP_API','Telkomsel','asia_pacific','API_KEY',true),
      ('Globe_PH','HTTP_API','Globe','asia_pacific','BASIC',true),
      ('Singtel_SG','HTTP_API','Singtel','asia_pacific','BASIC',true),
      ('Maxis_MY','HTTP_API','Maxis','asia_pacific','API_KEY',true),
      ('Telstra_RCS','RCS','Telstra','asia_pacific','API_KEY',true),
      ('GrameenPhone','HTTP_API','GP','bangladesh','API_KEY',true),
      ('Robi_BD','HTTP_API','Robi','bangladesh','BASIC',true),
      ('Banglalink','HTTP_API','Banglalink','bangladesh','API_KEY',true),
      ('Teletalk_BD','HTTP_API','Teletalk','bangladesh','API_KEY',true),
      ('GP_RCS','RCS','GP','bangladesh','API_KEY',true),
      ('BL_Flash','FLASH_SMS','Banglalink','bangladesh','API_KEY',true),
      ('GP_Flash','FLASH_SMS','GP','bangladesh','API_KEY',true),
      ('Airtel_IN','HTTP_API','Airtel','india','API_KEY',true),
      ('Jio_Platform','HTTP_API','Jio','india','BASIC',true),
      ('VI_India','HTTP_API','VodafoneIdea','india','API_KEY',true),
      ('BSNL_SMS','HTTP_API','BSNL','india','BASIC',true),
      ('Jio_RCS','RCS','Jio','india','API_KEY',true),
      ('Jio_Flash','FLASH_SMS','Jio','india','API_KEY',true),
      ('Airtel_Flash','FLASH_SMS','Airtel','india','API_KEY',true),
      ('MTS_Russia','HTTP_API','MTS','russia','API_KEY',true),
      ('Beeline_RU','HTTP_API','Beeline','russia','BASIC',true),
      ('MegaFon_RU','HTTP_API','MegaFon','russia','API_KEY',true),
      ('MTS_RCS','RCS','MTS','russia','API_KEY',true),
      ('ChinaMobile','HTTP_API','ChinaMobile','china','API_KEY',true),
      ('ChinaUnicom','HTTP_API','ChinaUnicom','china','BASIC',true),
      ('CMCC_RCS','RCS','CMCC','china','API_KEY',true),
      ('Digicel_FJ','HTTP_API','Digicel','oceania','API_KEY',true),
      ('Vodafone_FJ','HTTP_API','Vodafone','oceania','BASIC',true)
      ON CONFLICT DO NOTHING
    $ins$, tenant.schema_name);
    RAISE NOTICE 'Seeded connectors into %', tenant.schema_name;
  END LOOP;
END
$seed$;
