#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════
#  Net2APP — Residential Proxy Setup (3proxy + Tailscale)
#
#  Run ON THE RESIDENTIAL MACHINE (home PC / Raspberry Pi / old laptop that
#  sits on a residential internet connection). It:
#    1. Installs + authenticates Tailscale
#    2. Installs 3proxy
#    3. Writes /etc/3proxy/3proxy.cfg with a SOCKS5 proxy bound to the
#       Tailscale IP (never exposed to the public internet)
#    4. Starts 3proxy as a systemd service
#
#  Usage:  sudo bash setup-residential-proxy.sh
#
#  After it finishes:
#    • The machine's Tailscale IP + the proxy user/password are printed.
#    • Install Tailscale on the SaaS server too (`curl -fsSL
#      https://tailscale.com/install.sh | sh && sudo tailscale up`).
#    • Register the proxy in the dashboard (Settings → API Settings →
#      Proxy Setup, or Suppliers → Proxy Config) and press 🧪 Test to
#      verify the full chain before assigning it to OTT/Business API.
# ═══════════════════════════════════════════════════════════════════════
set -e

if [ "$EUID" -ne 0 ]; then exec sudo bash "$0" "$@"; fi

# ── Config (override via env, e.g. PROXY_PORT=1081 sudo bash setup...) ──
PROXY_USER="${PROXY_USER:-myproxyuser}"
# Generate a random password without depending on openssl (bare systems may
# lack it) — fall back to /dev/urandom if needed.
if [ -z "${PROXY_PASS:-}" ]; then
  if command -v openssl >/dev/null 2>&1; then
    PROXY_PASS="$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-16)"
  else
    PROXY_PASS="$(head -c 16 /dev/urandom | base64 | tr -d '/+=' | cut -c1-16)"
  fi
fi
PROXY_PORT="${PROXY_PORT:-1080}"
TAILSCALE_TAG="${TAILSCALE_TAG:-}"
TAILSCALE_AUTHKEY="${TAILSCALE_AUTHKEY:-}"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; RED='\033[0;31m'; NC='\033[0m'
ok(){ echo -e "${GREEN}[OK]${NC} $1"; }
info(){ echo -e "${YELLOW}[i]${NC} $1"; }
warn(){ echo -e "${RED}[!]${NC} $1"; }

echo ""
echo "════════════════════════════════════════════════════════"
echo "  Net2APP Residential Proxy Setup (3proxy + Tailscale)"
echo "════════════════════════════════════════════════════════"
echo ""

# ── 1. Detect distro for package manager ──
PKG="apt-get"
command -v apt-get >/dev/null 2>&1 || PKG="dnf"
command -v dnf >/dev/null 2>&1 || PKG="yum"
info "Using package manager: $PKG"

# ── 2. Install Tailscale ──
info "Installing Tailscale..."
if command -v tailscale >/dev/null 2>&1; then
  ok "Tailscale already installed"
else
  curl -fsSL https://tailscale.com/install.sh | sh
  ok "Tailscale installed"
fi

if tailscale status >/dev/null 2>&1; then
  ok "Tailscale already logged in"
else
  if [ -n "$TAILSCALE_AUTHKEY" ]; then
    tailscale up --authkey="$TAILSCALE_AUTHKEY" ${TAILSCALE_TAG:+--advertise-tags="$TAILSCALE_TAG"}
    ok "Tailscale authenticated (authkey)"
  else
    info "Run: sudo tailscale up ${TAILSCALE_TAG:+--advertise-tags=\"$TAILSCALE_TAG\"}"
    info "A browser URL will open — log in with the Tailscale account that also includes your SaaS server."
    sudo tailscale up ${TAILSCALE_TAG:+--advertise-tags="$TAILSCALE_TAG"}
    ok "Tailscale authenticated"
  fi
fi

TS_IP="$(tailscale ip -4 | head -1)"
if [ -z "$TS_IP" ]; then
  warn "Could not determine Tailscale IP — aborting."
  exit 1
fi
ok "Tailscale IP: $TS_IP"

# ── 3. Install 3proxy ──
info "Installing 3proxy..."
if command -v 3proxy >/dev/null 2>&1; then
  ok "3proxy already installed"
else
  case "$PKG" in
    apt-get) DEBIAN_FRONTEND=noninteractive apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq 3proxy ;;
    dnf)     dnf install -y -q 3proxy ;;
    yum)     yum install -y -q 3proxy ;;
  esac
  ok "3proxy installed"
fi

# ── 4. Write 3proxy config ──
CFG="/etc/3proxy/3proxy.cfg"
info "Writing $CFG (bound to Tailscale IP $TS_IP)..."
cat > "$CFG" <<EOF
# Generated by Net2APP setup-residential-proxy.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
nserver 8.8.8.8
nserver 1.1.1.1
nscache 65536
timeouts 1 5 30 60 180 1800 15 60

users ${PROXY_USER}:CL:${PROXY_PASS}

auth strong
allow ${PROXY_USER}
socks -p${PROXY_PORT} -e${TS_IP}
flush
EOF
ok "3proxy config written"

# ── 5. systemd service ──
# Resolve the actual 3proxy binary path (varies by distro: /usr/bin vs /usr/sbin).
THREEPROXY_BIN="$(command -v 3proxy || echo /usr/bin/3proxy)"
info "3proxy binary: $THREEPROXY_BIN"
if [ -d /etc/systemd/system ]; then
  cat > /etc/systemd/system/3proxy.service <<EOF
[Unit]
Description=3proxy Proxy Server
After=network.target

[Service]
ExecStart=${THREEPROXY_BIN} /etc/3proxy/3proxy.cfg
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable 3proxy >/dev/null 2>&1 || true
  systemctl restart 3proxy
  sleep 1
  if systemctl is-active --quiet 3proxy; then
    ok "3proxy service running"
  else
    warn "3proxy service failed to start — run: journalctl -u 3proxy -n 50"
  fi
else
  warn "No systemd found — start 3proxy manually: 3proxy $CFG"
fi

# ── 6. Optional: verify locally ──
info "Verifying SOCKS5 proxy from this machine..."
curl -s --max-time 8 --socks5 "${PROXY_USER}:${PROXY_PASS}@${TS_IP}:${PROXY_PORT}" https://api.ipify.org \
  && { echo "  ← egress IP through proxy (should be THIS machine's public IP)"; } \
  || warn "Local check failed (may be expected if this machine can't reach itself — test from the SaaS server instead)"

echo ""
echo "════════════════════════════════════════════════════════"
echo "  ✅ Residential proxy is ready"
echo "════════════════════════════════════════════════════════"
echo ""
echo -e "  ${CYAN}Tailscale IP:${NC}   ${TS_IP}"
echo -e "  ${CYAN}Port:${NC}          ${PROXY_PORT}"
echo -e "  ${CYAN}Protocol:${NC}      socks5"
echo -e "  ${CYAN}Username:${NC}      ${PROXY_USER}"
echo -e "  ${CYAN}Password:${NC}      ${PROXY_PASS}"
echo ""
echo "  Next steps:"
echo "    1. On the SaaS server:  curl -fsSL https://tailscale.com/install.sh | sh && sudo tailscale up"
echo "    2. Verify:              curl --socks5 ${PROXY_USER}:${PROXY_PASS}@${TS_IP}:${PROXY_PORT} https://api.ipify.org"
echo "    3. Add in dashboard (Suppliers → Proxy Config) then press 🧪 Test."
echo ""
