import { NextResponse } from "next/server";
import crypto from "crypto";
import { getTenantFromRequest, createProxyRegisterToken } from "@/lib/auth";
import { pool } from "@/db";
import { auditLog } from "@/lib/db-helpers";

// ═══════════════════════════════════════════════════════════════════════
//  Per-tenant 3proxy installer download.
//
//  Each request mints a FRESH credential pair + a short-lived (30 min)
//  registration token and returns a self-contained installer script
//  pre-configured for THIS tenant:
//    • its assigned server IP (tenants.smpp_server_ip) — shown as the
//      "serving server" and used to secure the config comments
//    • the dashboard origin (request URL) — the installer POSTs its new
//      Tailscale IP back to /api/tenant/proxy-config/register when done,
//      so the proxy row appears in the dashboard with zero manual entry
//    • unique SOCKS5 username/password baked into the 3proxy config
//
//  The script runs ON THE RESIDENTIAL MACHINE (home PC): it installs
//  Tailscale + 3proxy, writes /etc/3proxy/3proxy.cfg (or Windows service),
//  starts the proxy, and auto-registers with this server.
//
//  GET /api/tenant/proxy-config/download?os=linux|windows
// ═══════════════════════════════════════════════════════════════════════

const PROXY_PORT = 1080;

function randomUsername(): string {
  return "n2p_" + crypto.randomBytes(5).toString("hex");
}

function randomPassword(): string {
  // Alphanumeric only — safe to embed in bash, batch, PowerShell and JSON
  // regardless of quoting.
  return crypto.randomBytes(24).toString("base64").replace(/[^a-zA-Z0-9]/g, "").slice(0, 16);
}

function slugify(name: string): string {
  const s = (name || "tenant").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
  return s || "tenant";
}

// ── Linux installer (bash — apt/dnf/yum + systemd) ─────────────────────
export function buildLinuxScript(opts: {
  companyName: string; serverIp: string; serverUrl: string;
  username: string; password: string; regToken: string;
  authKey: string;
  advertiseTags: string;
}): string {
  const { companyName, serverIp, serverUrl, username, password, regToken, authKey, advertiseTags } = opts;
  return `#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════
#  Net2APP — Residential Proxy Setup for ${companyName} (3proxy + Tailscale)
#
#  Your assigned Net2APP server : ${serverIp}
#  This installer will:
#    1. Install + authenticate Tailscale
#    2. Install 3proxy
#    3. Write a SOCKS5 config bound to the Tailscale IP (never public)
#    4. Start 3proxy as a systemd service
#    5. Register the proxy in your Net2APP dashboard automatically
#
#  Run ON THE RESIDENTIAL MACHINE (home PC on your home internet):
#      sudo bash net2app-3proxy-setup.sh
#
#  🔒 Contains your proxy credentials — do not share this file.
#  Optional: override the embedded auto-connect key / tags with
#      TAILSCALE_AUTHKEY=tskey-auth-... TAILSCALE_ADVERTISE_TAGS=tag:client sudo bash net2app-3proxy-setup.sh
# ═══════════════════════════════════════════════════════════════════════
set -e
if [ "$EUID" -ne 0 ]; then exec sudo bash "$0" "$@"; fi

# ── Pre-generated by the Net2APP dashboard ──
PROXY_USER="${username}"
PROXY_PASS="${password}"
PROXY_PORT="${PROXY_PORT}"
SERVER_IP="${serverIp}"
SERVER_URL="${serverUrl}"
REG_TOKEN="${regToken}"
# Auto-connect key (embedded by the dashboard; a runtime env value wins)
TAILSCALE_AUTHKEY="\${TAILSCALE_AUTHKEY:-${authKey}}"
# Advertise tags for tag-scoped auth keys (comma-separated, e.g. tag:client)
TAILSCALE_ADVERTISE_TAGS="\${TAILSCALE_ADVERTISE_TAGS:-${advertiseTags}}"

GREEN='\\033[0;32m'; YELLOW='\\033[1;33m'; CYAN='\\033[0;36m'; RED='\\033[0;31m'; NC='\\033[0m'
ok(){ echo -e "\${GREEN}[OK]\${NC} $1"; }
info(){ echo -e "\${YELLOW}[i]\${NC} $1"; }
warn(){ echo -e "\${RED}[!]\${NC} $1"; }

echo ""
echo "════════════════════════════════════════════════════════"
echo "  Net2APP Residential Proxy Setup for ${companyName}"
echo "  Serving server: ${serverIp}"
echo "════════════════════════════════════════════════════════"
echo ""

# ── 1. Detect package manager ──
PKG="apt-get"
command -v apt-get >/dev/null 2>&1 || PKG="dnf"
command -v dnf >/dev/null 2>&1 || PKG="yum"
info "Using package manager: $PKG"

# ── 2. Tailscale ──
info "Installing Tailscale..."
if command -v tailscale >/dev/null 2>&1; then
  ok "Tailscale already installed"
else
  curl -fsSL https://tailscale.com/install.sh | sh
  ok "Tailscale installed"
fi

if tailscale status >/dev/null 2>&1; then
  ok "Tailscale already logged in"
else
  if [ -n "$TAILSCALE_AUTHKEY" ]; then
    if [ -n "$TAILSCALE_ADVERTISE_TAGS" ]; then
      tailscale up --authkey="$TAILSCALE_AUTHKEY" --advertise-tags="$TAILSCALE_ADVERTISE_TAGS"
    else
      tailscale up --authkey="$TAILSCALE_AUTHKEY"
    fi
    ok "Tailscale authenticated (authkey)"
  else
    info "Running 'sudo tailscale up' — a browser URL will open. Log in with the"
    info "Tailscale account that ALSO includes your Net2APP server (see Step 3 in the guide)."
    tailscale up
    ok "Tailscale authenticated"
  fi
fi

TS_IP="$(tailscale ip -4 | head -1)"
if [ -z "$TS_IP" ]; then
  warn "Could not determine Tailscale IP — aborting."
  exit 1
fi
ok "Tailscale IP: $TS_IP"

# ── 3. Install 3proxy ──
info "Installing 3proxy..."
if ! command -v 3proxy >/dev/null 2>&1; then
  case "$PKG" in
    apt-get) DEBIAN_FRONTEND=noninteractive apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq 3proxy || true ;;
    dnf)     dnf install -y -q 3proxy || true ;;
    yum)     yum install -y -q 3proxy || true ;;
  esac
fi
if ! command -v 3proxy >/dev/null 2>&1; then
  info "Package unavailable — building 3proxy from source (best effort)..."
  if command -v apt-get >/dev/null 2>&1; then
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq gcc make git >/dev/null 2>&1 || true
  fi
  if [ ! -d /tmp/3proxy-build ]; then
    git clone --depth 1 https://github.com/3proxy/3proxy.git /tmp/3proxy-build 2>/dev/null || true
  fi
  if [ -d /tmp/3proxy-build ]; then
    ( cd /tmp/3proxy-build && make -f Makefile.Linux >/dev/null 2>&1 || make >/dev/null 2>&1 ) || true
    if [ -f /tmp/3proxy-build/src/3proxy ]; then
      cp /tmp/3proxy-build/src/3proxy /usr/local/bin/3proxy
      chmod +x /usr/local/bin/3proxy
      ok "3proxy built from source"
    fi
  fi
fi
if ! command -v 3proxy >/dev/null 2>&1; then
  warn "3proxy could not be installed automatically — install it manually, then re-run this script."
  exit 1
fi
ok "3proxy installed"

# ── 4. Write 3proxy config ──
CFG="/etc/3proxy/3proxy.cfg"
info "Writing $CFG (bound to Tailscale IP $TS_IP)..."
cat > "$CFG" <<EOF
# Generated by Net2APP for ${companyName} — serving server ${serverIp}
nserver 8.8.8.8
nserver 1.1.1.1
nscache 65536
timeouts 1 5 30 60 180 1800 15 60

users $PROXY_USER:CL:$PROXY_PASS

auth strong
allow $PROXY_USER
socks -p$PROXY_PORT -e$TS_IP
flush
EOF
ok "3proxy config written"

# ── 5. systemd service ──
THREEPROXY_BIN="$(command -v 3proxy || echo /usr/local/bin/3proxy)"
info "3proxy binary: $THREEPROXY_BIN"
if [ -d /etc/systemd/system ]; then
  cat > /etc/systemd/system/3proxy.service <<EOF
[Unit]
Description=3proxy Proxy Server (Net2APP ${companyName})
After=network.target

[Service]
ExecStart=\${THREEPROXY_BIN} /etc/3proxy/3proxy.cfg
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable 3proxy >/dev/null 2>&1 || true
  systemctl restart 3proxy
  sleep 1
  if systemctl is-active --quiet 3proxy; then
    ok "3proxy service running"
  else
    warn "3proxy service failed to start — run: journalctl -u 3proxy -n 50"
  fi
else
  warn "No systemd found — start 3proxy manually: 3proxy $CFG"
fi

# ── 6. Register with the Net2APP dashboard ──
info "Registering proxy with your Net2APP dashboard ($SERVER_URL)..."
if [ -n "$SERVER_URL" ] && [ -n "$REG_TOKEN" ]; then
  RESP="$(curl -sS -m 25 -X POST "$SERVER_URL/api/tenant/proxy-config/register" \\
    -H "Content-Type: application/json" \\
    -d '{"token":"'"$REG_TOKEN"'","host":"'"$TS_IP"'","name":"Home 3proxy (auto)"}' 2>&1 || true)"
  case "$RESP" in
    *'"ok":true'*|*'"ok": true'*) ok "Registered automatically — the proxy row is now in your dashboard (host $TS_IP)" ;;
    *) warn "Auto-register failed: $RESP" ; warn "Add the proxy manually in the dashboard: host=$TS_IP port=$PROXY_PORT user=$PROXY_USER" ;;
  esac
fi

echo ""
echo "════════════════════════════════════════════════════════"
echo "  ✅ Residential proxy is ready"
echo "════════════════════════════════════════════════════════"
echo ""
echo -e "  \${CYAN}Tailscale IP:\${NC}   $TS_IP"
echo -e "  \${CYAN}Port:\${NC}          $PROXY_PORT"
echo -e "  \${CYAN}Protocol:\${NC}      socks5"
echo -e "  \${CYAN}Username:\${NC}      $PROXY_USER"
echo -e "  \${CYAN}Password:\${NC}      $PROXY_PASS"
echo -e "  \${CYAN}Serving server:\${NC} $SERVER_IP"
echo ""
echo "  Next steps:"
echo "    1. If auto-register failed, add the proxy in your dashboard"
echo "       (Proxy Configuration → + Add Proxy) using the values above."
echo "    2. Test it there with the 🧪 Test button."
echo ""
`;
}

// ── Windows installer (.bat bootstrap + embedded PowerShell) ────────────
export function buildWindowsScript(opts: {
  companyName: string; serverIp: string; serverUrl: string;
  username: string; password: string; regToken: string;
  authKey: string;
  advertiseTags: string;
}): string {
  const { companyName, serverIp, serverUrl, username, password, regToken, authKey, advertiseTags } = opts;

  // The PowerShell installer is embedded base64 (UTF-16LE) and decoded by
  // certutil at runtime — avoids every cmd.exe quoting edge case.
  const ps1 = `$ErrorActionPreference = "Stop"
$SERVER_URL = "${serverUrl}"
$SERVER_IP = "${serverIp}"
$REG_TOKEN = "${regToken}"
$PROXY_USER = "${username}"
$PROXY_PASS = "${password}"
$PROXY_PORT = ${PROXY_PORT}
$AUTHKEY = "${authKey}"
$ADVERTISE_TAGS = "${advertiseTags}"
$ARCHIVE = "https://github.com/3proxy/3proxy/releases/download/0.9.8/3proxy-0.9.8-x64.zip"
$TSMSI = "https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi"

Write-Host ""
Write-Host ("  Net2APP Residential Proxy Setup for " + "${companyName}") -ForegroundColor Green
Write-Host ("  Serving server : " + $SERVER_IP) -ForegroundColor Cyan
Write-Host ""

# 1) Tailscale
$tailscale = Join-Path $env:ProgramFiles "Tailscale\\tailscale.exe"
if (-not (Test-Path $tailscale)) {
    Write-Host "[1/4] Installing Tailscale..." -ForegroundColor Yellow
    try { winget install -e --id Tailscale.Tailscale --accept-package-agreements --accept-source-agreements | Out-Null } catch { }
    if (-not (Test-Path $tailscale)) {
        $msi = Join-Path $env:TEMP "tailscale-setup.msi"
        Invoke-WebRequest -Uri $TSMSI -OutFile $msi -UseBasicParsing
        Start-Process msiexec -ArgumentList ('/i "' + $msi + '" /qn') -Wait
    }
}
$tsip = ""
if (Test-Path $tailscale) {
    $tsip = (& $tailscale ip -4 2>$null | Select-Object -First 1)
}
if (-not $tsip) {
    if ($AUTHKEY) {
        Write-Host "Connecting automatically with the embedded Tailscale auth key..." -ForegroundColor Green
        if ($ADVERTISE_TAGS) {
            & $tailscale up --authkey=$AUTHKEY --advertise-tags=$ADVERTISE_TAGS | Out-Null
        }
        else {
            & $tailscale up --authkey=$AUTHKEY | Out-Null
        }
    }
    else {
        Write-Host "Starting Tailscale - a browser window will open. Log in with the account that" -ForegroundColor Yellow
        Write-Host "includes your Net2APP server." -ForegroundColor Yellow
        & $tailscale up | Out-Null
    }
    $tsip = (& $tailscale ip -4 | Select-Object -First 1)
}
if (-not $tsip) { throw "Could not determine Tailscale IP - is Tailscale running?" }
Write-Host ("Tailscale IP  : " + $tsip) -ForegroundColor Cyan

# 2) 3proxy
$3pDir = Join-Path $env:ProgramFiles "3proxy"
$3pExe = Join-Path $3pDir "3proxy.exe"
if (-not (Test-Path $3pExe)) {
    Write-Host "[2/4] Downloading 3proxy..." -ForegroundColor Yellow
    $zip = Join-Path $env:TEMP "3proxy.zip"
    Invoke-WebRequest -Uri $ARCHIVE -OutFile $zip -UseBasicParsing
    Expand-Archive -Path $zip -DestinationPath $3pDir -Force
    $found = Get-ChildItem -Path $3pDir -Recurse -Filter "3proxy.exe" | Select-Object -First 1
    if (-not $found) { throw "3proxy.exe not found in the downloaded archive" }
    Copy-Item -Path $found.FullName -Destination $3pExe -Force
}

# 3) Config
$cfg = Join-Path $3pDir "3proxy.cfg"
@"
# Generated by Net2APP for ${companyName} - serving server ${serverIp}
nserver 8.8.8.8
nserver 1.1.1.1
nscache 65536
timeouts 1 5 30 60 180 1800 15 60

users $PROXY_USER:CL:$PROXY_PASS

auth strong
allow $PROXY_USER
socks -p$PROXY_PORT -e$tsip
flush
"@ | Set-Content -Path $cfg -Encoding Ascii

# 4) Service
Write-Host "[3/4] Installing 3proxy service..." -ForegroundColor Yellow
$binPath = '"' + $3pExe + '" "' + $cfg + '"'
$svc = Get-Service -Name "3proxy" -ErrorAction SilentlyContinue
if (-not $svc) {
    & sc.exe create 3proxy start= auto binPath= $binPath | Out-Null
}
& sc.exe config 3proxy binPath= $binPath | Out-Null
& sc.exe config 3proxy start= auto | Out-Null
& sc.exe start 3proxy | Out-Null

# 5) Auto-register with the Net2APP dashboard
Write-Host "[4/4] Registering with your Net2APP dashboard..." -ForegroundColor Yellow
try {
    $body = @{ token = $REG_TOKEN; host = $tsip; name = "Home 3proxy (auto)" } | ConvertTo-Json
    $r = Invoke-RestMethod -Method Post -Uri ($SERVER_URL + "/api/tenant/proxy-config/register") -ContentType "application/json" -Body $body -TimeoutSec 25
    if ($r.ok) { Write-Host "Registered automatically! Proxy row added to your dashboard." -ForegroundColor Green }
    else { Write-Host ("Auto-register returned an error: " + $r.error) -ForegroundColor Red }
}
catch {
    Write-Host ("Auto-register failed: " + $_.Exception.Message) -ForegroundColor Red
    Write-Host "Add the proxy manually in the dashboard using the values below."
}

Write-Host ""
Write-Host "=============== Residential proxy ready ===============" -ForegroundColor Green
Write-Host ("  Tailscale IP : " + $tsip)
Write-Host ("  Port         : " + $PROXY_PORT)
Write-Host "  Protocol     : socks5"
Write-Host ("  Username     : " + $PROXY_USER)
Write-Host ("  Password     : " + $PROXY_PASS)
Write-Host ("  Server IP    : " + $SERVER_IP)
Write-Host "======================================================="
Read-Host "Press Enter to close"
`;
  const ps1B64 = Buffer.from(ps1, "utf16le").toString("base64");

  // cmd.exe truncates any single batch line at 8191 chars, so the base64
  // payload is written to the .b64 file in chunks (certutil tolerates
  // line-wrapped base64). Keep every echo line comfortably under the limit.
  const B64_CHUNK = 6000;
  const b64Lines: string[] = [];
  for (let i = 0; i < ps1B64.length; i += B64_CHUNK) {
    b64Lines.push(`>>"%B64%" echo ${ps1B64.slice(i, i + B64_CHUNK)}`);
  }

  return `@echo off
setlocal EnableExtensions
title Net2APP 3proxy Installer

net session >nul 2>&1
if %errorlevel% neq 0 (
  powershell -NoProfile -ExecutionPolicy Bypass -Command "Start-Process -FilePath '%~f0' -Verb RunAs"
  exit /b
)

echo.
echo  Net2APP Residential Proxy Setup (3proxy + Tailscale)
echo  Account          : ${companyName}
echo  Assigned server  : ${serverIp}
echo  Proxy user       : ${username}
echo  Port             : ${PROXY_PORT}
echo.

set "B64=%TEMP%\\n2p_setup.b64"
set "PS1FILE=%TEMP%\\n2p_setup.ps1"

> "%B64%" echo -----BEGIN CERTIFICATE-----
${b64Lines.join("\n")}
>>"%B64%" echo -----END CERTIFICATE-----
certutil -decode "%B64%" "%PS1FILE%" >nul 2>&1
if errorlevel 1 (
  echo ERROR: could not prepare installer.
  pause
  exit /b 1
)

powershell -NoProfile -ExecutionPolicy Bypass -File "%PS1FILE%"
exit /b %errorlevel%
`;
}

// ── Route ──────────────────────────────────────────────────────────────
export async function GET(request: Request) {
  const tenant = getTenantFromRequest(request);
  if (!tenant) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const url = new URL(request.url);
  const os = url.searchParams.get("os") === "windows" ? "windows" : "linux";

  // Tenant's assigned server IP (used as the "serving server" in the script).
  // Kept in its own query so the serving-server IP is never lost even if the
  // approval column is missing pre-migration.
  let serverIp = "0.0.0.0";
  try {
    const res = await pool.query("SELECT smpp_server_ip FROM tenants WHERE id = $1", [tenant.tenantId]);
    if (res.rows.length > 0 && res.rows[0].smpp_server_ip) serverIp = String(res.rows[0].smpp_server_ip);
  } catch { /* keep 0.0.0.0 */ }

  // Super-admin approval flag: only APPROVED tenants get the embedded
  // auto-connect key/tags. Fail-closed — a missing/NULL column (pre-migration)
  // means a plain installer, never an unapproved key embed.
  let autoConnectEnabled = false;
  try {
    const res = await pool.query("SELECT auto_connect_enabled FROM tenants WHERE id = $1", [tenant.tenantId]);
    if (res.rows.length > 0 && res.rows[0].auto_connect_enabled === true) autoConnectEnabled = true;
  } catch { /* keep false */ }

  // Platform Tailscale auth key (set by super admin) — makes the installer
  // connect the home PC to the tailnet automatically, no browser login.
  let tailscaleAuthKey = "";
  try {
    const keyRes = await pool.query("SELECT value FROM platform_settings WHERE key = 'tailscaleAuthKey'");
    if (keyRes.rows.length > 0 && keyRes.rows[0].value) {
      // Sanitize for embedding in bash/PS1 — keys are [a-zA-Z0-9-] only.
      tailscaleAuthKey = String(keyRes.rows[0].value).replace(/[^a-zA-Z0-9-]/g, "").trim();
    }
  } catch { /* no key configured */ }

  // Platform Tailscale advertise tags (set by super admin) — required for
  // tag-scoped auth keys: `tailscale up --advertise-tags=...`. Sanitized for
  // safe embedding in bash/PS1 (letters, digits, tag:, commas, dashes, spaces).
  let tailscaleAdvertiseTags = "";
  try {
    const tagsRes = await pool.query("SELECT value FROM platform_settings WHERE key = 'tailscaleAdvertiseTags'");
    if (tagsRes.rows.length > 0 && tagsRes.rows[0].value) {
      tailscaleAdvertiseTags = String(tagsRes.rows[0].value).replace(/[^a-zA-Z0-9:,\- ]/g, "").trim();
    }
  } catch { /* no tags configured */ }

  // Per-tenant approval gate: unapproved tenants download a plain installer
  // (interactive login fallback) even when the platform key is configured.
  if (!autoConnectEnabled) {
    tailscaleAuthKey = "";
    tailscaleAdvertiseTags = "";
  }

  // The origin is how the home PC reaches this server to auto-register.
  // (If the platform is ever served behind a fixed domain, prefer an env-based
  // base URL over the Host header — see reviewer note.)
  const serverUrl = url.origin; // e.g. https://net2app.com
  // Only safe characters may be interpolated into bash/PS1/bat + the systemd
  // unit — a company name with quotes/newlines must not corrupt the script.
  const companyName = (tenant.companyName || "my-account")
    .replace(/[^a-zA-Z0-9 ._\-]/g, "")
    .trim()
    .slice(0, 60) || "my-account";
  const username = randomUsername();
  const password = randomPassword();
  const regToken = createProxyRegisterToken({
    scope: "proxy-register",
    tenantId: tenant.tenantId,
    schemaName: tenant.schemaName,
    username,
    password,
    port: PROXY_PORT,
  });

  const opts = {
    companyName, serverIp, serverUrl, username, password, regToken,
    authKey: tailscaleAuthKey,
    advertiseTags: tailscaleAdvertiseTags,
  };
  const body = os === "windows" ? buildWindowsScript(opts) : buildLinuxScript(opts);
  const filename = `net2app-3proxy-${slugify(companyName)}.${os === "windows" ? "bat" : "sh"}`;

  // ── Audit trail: record every installer download (esp. ones embedding the
  //    Tailscale auth key — those carry tailnet access). Fire-and-forget; the
  //    helper swallows errors so a log failure can never break the download. ──
  const clientIp =
    request.headers.get("cf-connecting-ip") ||
    request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ||
    "unknown";
  void auditLog(
    "proxy_installer",
    null,
    "DOWNLOAD",
    tenant.email,
    undefined,
    { os, filename, embeddedAuthKey: tailscaleAuthKey !== "", autoConnectEnabled },
    tenant.tenantId,
    clientIp
  ).catch(() => {});

  return new NextResponse(body, {
    status: 200,
    headers: {
      "Content-Type": os === "windows" ? "application/x-msdownload" : "text/x-shellscript; charset=utf-8",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control": "no-store",
      "X-Net2App-Proxy-Server": serverIp,
    },
  });
}
